server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&serverTimezone=UTC
    data-username: root
    data-password: courage
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6380
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
    timeout:
    connect-timeout:

